using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class pause_menu : MonoBehaviour
{

    public static bool GameIsPaused = false;

    public GameObject pauseMenuUI;

    // Update is called once per frame
    void Update()
    {
        // kill player statement
        //if (PlayerHealth.currentHealth <= 0) 
        //{ 
        //    Pause();
        //}
        if (MeleeController.isAlive == false)
        {
            // PlayerMovement.animator.SetTrigger("Die");
            Debug.Log("pause_menu you died! in");
            Pause();
        }
        // if (PlayerHealth.isAlive == false)
        // {
        //     PlayerMovement.animator.SetTrigger("Die");
        //     Debug.Log("pause_menu you died! in");
        //     Pause();
        // }
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            if (GameIsPaused)
            {
                Resume();
            }
            else
            {
                Pause();
            }
        }

    }

    public void Resume()
    {
        pauseMenuUI.SetActive(false);
        Time.timeScale = 1f;
        GameIsPaused = false;
    }
    public void Pause()
    {
        pauseMenuUI.SetActive(true);
        Time.timeScale = 1f;
        GameIsPaused = true;
    }

    public void LoadMenu()
    {
        Debug.Log("LoadMenu");
        Time.timeScale = 1f;
        SceneManager.LoadScene("menu_main");
    }

    public void QuitGame()
    {
        Debug.Log("QuitGame");
        Application.Quit();
    }
}
